packages:
  - 'apps/*'
  - 'packages/*'

verifyDepsBeforeRun: false

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@nestjs/core'
  - esbuild
  - prisma

allowBuilds:
  '@nestjs/core': true
  esbuild: true
